### ISSUE TITLE
Task: Propose updates to the DID Resolution Protocol to include Problem Reports

### ISSUE THREAD

**Issue by dbluhm** [sicpa-dlab/acapy-resolver-didcomm#17]
The RFC does not include any notion of reporting errors and other failure conditions in the protocol. To overcome this we utilized an adopted Problem Report message to great effect. We should contribute this concept to the RFC.

**Comment by Luis-GA** [comment]
I have written this. Do you think it is a good approach? is it something missing?

**Comment by dbluhm** [comment]
We've got the code and it is good! This task is referring to updating the protocol RFC to reflect what we've done in code.

**Comment by Luis-GA** [comment]
I was talking about the RFC documentation, isn't it?

**Comment by dbluhm** [comment]
Sorry, I'll be more specific :slightly_smiling_face:
The RFC I'm referencing is found here: https://github.com/hyperledger/aries-rfcs/blob/master/features/0124-did-resolution-protocol/README.md

This is the specification that implementers of the DID Resolution protocol are supposed to follow. It doesn't include any messages returned from resolver to requester to inform them of failure to resolve -- which is what we did in our plugin and ultimately is a requirement for a complete protocol flow. So it makes sense for us to update the language in the RFC to reflect what we did in the code.

Hopefully that clarifies the intent of this task.

**Comment by Luis-GA** [comment]
Nice, we are talking about the same! 
I have done a draft of the spec here https://github.com/Luis-GA/aries-rfcs/commit/0c5ec3be1b199cde8299387a6561b126f90afa1e Do you think that something is missing in my approach?

**Comment by dbluhm** [comment]
Oh :facepalm: should have followed your link! Sorry about that lol

**Comment by dbluhm** [comment]
We should get these changes opened as a draft PR so we can comment and leave feedback more easily. We can make this a PR to the main repo or we can open it against a fork (i.e. mine or one in sicpa-dlab)

**Comment by Luis-GA** [comment]
https://github.com/hyperledger/aries-rfcs/pull/655
